// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CodeAnalysis struct {
	Feedback    string   `json:"feedback"`
	Suggestions []string `json:"suggestions"`
	Quality     string   `json:"quality"`
	Timestamp   string   `json:"timestamp"`
}

type CodeSubmission struct {
	SessionID string        `json:"sessionId"`
	Code      string        `json:"code"`
	Language  string        `json:"language"`
	Timestamp string        `json:"timestamp"`
	Analysis  *CodeAnalysis `json:"analysis,omitempty"`
}

type ExecutionResult struct {
	SessionID     string  `json:"sessionId"`
	Output        string  `json:"output"`
	Error         *string `json:"error,omitempty"`
	ExitCode      int     `json:"exitCode"`
	ExecutionTime float64 `json:"executionTime"`
	Timestamp     string  `json:"timestamp"`
}

type Interview struct {
	ID             string     `json:"id"`
	SessionID      string     `json:"sessionId"`
	UserID         string     `json:"userId"`
	Difficulty     string     `json:"difficulty"`
	Status         string     `json:"status"`
	StartedAt      string     `json:"startedAt"`
	EndedAt        *string    `json:"endedAt,omitempty"`
	CurrentProblem *Problem   `json:"currentProblem,omitempty"`
	Messages       []*Message `json:"messages"`
}

type Message struct {
	ID          string `json:"id"`
	SessionID   string `json:"sessionId"`
	Speaker     string `json:"speaker"`
	Content     string `json:"content"`
	Timestamp   string `json:"timestamp"`
	MessageType string `json:"messageType"`
}

type Mutation struct {
}

type Problem struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Difficulty  string      `json:"difficulty"`
	Topics      []string    `json:"topics"`
	StarterCode *string     `json:"starterCode,omitempty"`
	TestCases   []*TestCase `json:"testCases"`
}

type Query struct {
}

type Subscription struct {
}

type TestCase struct {
	Input          string  `json:"input"`
	ExpectedOutput string  `json:"expectedOutput"`
	Description    *string `json:"description,omitempty"`
}
